version: '1.0'
services:
  php:
    container_name: sentinel-php
    build:
      context: ./php
    volumes:
      - ./app-site:/var/www/app-site
    networks:
      - default
  nginx:
    container_name: sentinel-nginx
    image: nginx:stable-alpine
    ports:
      - ${PORT_APP_SITE}:80
    links:
      - php
    volumes:
      - ./app-site:/var/www/app-site
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
