services:
  php:
    container_name: sentinel-php
    env_file: ".env"
    build:
      context: ./php
    volumes:
      - ./app-site:/var/www/app-site
      - './camera_picture:/camera_picture'
    networks:
      - default
  nginx:
    container_name: sentinel-nginx
    image: nginx:stable-alpine
    ports:
      - ${PORT_APP_SITE}:80
    links:
      - php
    volumes:
      - ./app-site:/var/www/app-site
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
  mariadb:
      image: mariadb:latest
      ports:
        - "3307:3306"
      env_file: ".env"