services:
  php:
    container_name: sentinel-php
    privileged: true
    env_file: ".env"
    restart: always
    build:
      context: ./php
    volumes:
      - ./app-site:/var/www/app-site
      - ./camera_pictures:/camera_pictures
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
  nginx:
    container_name: sentinel-nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - ${PORT_APP_SITE}:80
    links:
      - php
    volumes:
      - ./app-site:/var/www/app-site
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
  mariadb:
      image: mariadb:latest
      ports:
        - "3307:3306"
      env_file: ".env"
      restart: always